### ISSUE TITLE
CrashLoopBackOff on nil pointer deref

### ISSUE THREAD

**Issue by ismith** [honeycombio/honeycomb-kubernetes-agent#204]
**Versions**
2.2.1

**Steps to reproduce**

1. Unclear - but I've seen this twice today in dogfood, on different pods.

```
time="2021-12-29T18:20:04Z" level=info msg="Done tailing file" filePath=/var/log/pods/honeycomb-dogfood_basset-27346685-x7ztx_b9bf7535-88e7-486d-b60a-0ab718c596bd/basset/0.log
time="2021-12-29T18:21:00Z" level=info msg="Setting up watcher for pod" Name=basset-27346701-tz9hl UID=7b52bcb8-975c-4bc4-b277-ad3af9b98e1d
time="2021-12-29T18:21:00Z" level=info msg="starting watcher for pod" labelselector="app,app!=honeycomb-agent" name=basset-27346701-tz9hl namespace=honeycomb-dogfood uid=7b52bcb8-975c-4bc4-b277-ad3af9b98e1d
time="2021-12-29T18:21:02Z" level=info msg="Log pattern" log pattern="/var/log/pods/honeycomb-dogfood_basset-27346701-tz9hl_7b52bcb8-975c-4bc4-b277-ad3af9b98e1d/*/*"
time="2021-12-29T18:21:02Z" level=info msg="Initializing file handler" parser=nop path=/var/log/pods/honeycomb-dogfood_basset-27346701-tz9hl_7b52bcb8-975c-4bc4-b277-ad3af9b98e1d/basset/0.log
time="2021-12-29T18:21:02Z" level=info msg="no prior tail state found" detail="key not found" path=/var/log/pods/honeycomb-dogfood_basset-27346701-tz9hl_7b52bcb8-975c-4bc4-b277-ad3af9b98e1d/basset/0.log
time="2021-12-29T18:21:02Z" level=info msg="Tailing file" offset=0 path=/var/log/pods/honeycomb-dogfood_basset-27346701-tz9hl_7b52bcb8-975c-4bc4-b277-ad3af9b98e1d/basset/0.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x64c5a4]

goroutine 65 [running]:
github.com/honeycombio/honeycomb-kubernetes-agent/metrics.getPodResource(0x400057c140, 0x4000b0f320, 0x12, 0x4000b0f338, 0x11, 0x4000b9e2a0, 0x24, 0x0, 0xed95e9e0c, 0x1819560, ...)
	/home/circleci/project/metrics/resource.go:55 +0x2a4
github.com/honeycombio/honeycomb-kubernetes-agent/metrics.(*Processor).GenerateMetricsData(0x4000b8a070, 0x4002452000, 0x4000c0b4a0, 0x4000ae5620, 0x1, 0xa2c7d202020200a, 0x6d656d2220202020)
	/home/circleci/project/metrics/processor.go:41 +0x25c
github.com/honeycombio/honeycomb-kubernetes-agent/service.(*runnable).Run(0x40001cfd50, 0x400298bc10, 0x1)
	/home/circleci/project/service/runnable.go:82 +0x3c4
github.com/honeycombio/honeycomb-kubernetes-agent/interval.(*Runner).run(0x4000a72f40, 0x0, 0x0)
	/home/circleci/project/interval/interval_runner.go:72 +0xa4
github.com/honeycombio/honeycomb-kubernetes-agent/interval.(*Runner).Start(0x4000a72f40, 0x0, 0x0)
	/home/circleci/project/interval/interval_runner.go:50 +0x1e4
github.com/honeycombio/honeycomb-kubernetes-agent/service.(*Service).Start.func1(0x40001cfb90)
	/home/circleci/project/service/service.go:138 +0x2c
created by github.com/honeycombio/honeycomb-kubernetes-agent/service.(*Service).Start
	/home/circleci/project/service/service.go:137 +0x458
```

**Additional context**

**Comment by ismith** [comment]
Easy enough to clean up by deleting the offending honeycomb-agent pod, but ... obviously that's a manual intervention I'd prefer to avoid.  Caught by our new trigger, which alerts on crashloopbackoff, not sure if it's new or not.

**Comment by ismith** [comment]
Perhaps a panic-catcher + stack trace and re-panic is the right pattern here?

**Comment by JamieDanielson** [comment]
[https://github.com/honeycombio/honeycomb-kubernetes-agent/blob/main/metrics/resource.go#L55](https://github.com/honeycombio/honeycomb-kubernetes-agent/blob/main/metrics/resource.go#L55)

Looks like the error was thrown on `s.CPU.Time.Time`. Though `Time` is a required field on the `CPUStats` struct, the `CPUStats` are optional on the `NodeStats` struct. We can check for existence of CPUStats, but if it does not exist, I'm not clear on what the timestamp should be for the Resource. There is a StartTime on `NodeStats` but not sure if it should be that, or 0...

@puckpuck any thoughts on what the Timestamp should be set to if there are no CPUStats available?

**Comment by puckpuck** [comment]
There are multiple stats that are collected, CPU, Memory, network, FileSystem, etc.  Are they all nil?

If all are nil, I think we should omit stats accumulation for the node on that cycle.
