### ISSUE TITLE
SegFault using k8s helm installation

### ISSUE THREAD

**Issue by davidbrowning** [honeycombio/honeycomb-kubernetes-agent#261]
**Versions**
`CHART_VERSION: 1.5.0`
`Image: honeycombio/honeycomb-kubernetes-agent:2.5.0`
```
$ helm ls -n honeycomb
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
honeycomb	honeycomb	1       	2022-05-20 19:27:23.048453055 +0000 UTC	deployed	honeycomb-1.5.0	2.5.0
```
**Steps to reproduce**
1. HNY agent installed on production cluster is crashing. We used the helm chart to deploy it. No cpu/memory requests or limits have been set on the daemonset
2. segfault from logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa81629]
goroutine 13 [running]:
[github.com/honeycombio/honeycomb-kubernetes-agent/metrics.(*PodMetadata).GetCpuLimit(0x1304120)](http://github.com/honeycombio/honeycomb-kubernetes-agent/metrics.(*PodMetadata).GetCpuLimit(0x1304120))
	[github.com/honeycombio/honeycomb-kubernetes-agent/metrics/metadata.go:102](http://github.com/honeycombio/honeycomb-kubernetes-agent/metrics/metadata.go:102) +0x29
[github.com/honeycombio/honeycomb-kubernetes-agent/metrics.(*MetricDataAccumulator).podStats(0xc00057ae48](http://github.com/honeycombio/honeycomb-kubernetes-agent/metrics.(*MetricDataAccumulator).podStats(0xc00057ae48), 0xc0000a48c0, {{{0xc001418ae0, 0x2d}, {0xc001416950, 0x2}, {0xc001418b10, 0x24}}, {{0x0, 0xeda205649, ...}}, ...})
	[github.com/honeycombio/honeycomb-kubernetes-agent/metrics/accumulator.go:66](http://github.com/honeycombio/honeycomb-kubernetes-agent/metrics/accumulator.go:66) +0x1c9
[github.com/honeycombio/honeycomb-kubernetes-agent/metrics.(*Processor).GenerateMetricsData(0xc000382008](http://github.com/honeycombio/honeycomb-kubernetes-agent/metrics.(*Processor).GenerateMetricsData(0xc000382008), 0xc0012eeb40, 0xc001931290, 0xc0007f0900)
	[github.com/honeycombio/honeycomb-kubernetes-agent/metrics/processor.go:37](http://github.com/honeycombio/honeycomb-kubernetes-agent/metrics/processor.go:37) +0x285
[github.com/honeycombio/honeycomb-kubernetes-agent/service.(*runnable).Run(0xc0007f6140)](http://github.com/honeycombio/honeycomb-kubernetes-agent/service.(*runnable).Run(0xc0007f6140))
	[github.com/honeycombio/honeycomb-kubernetes-agent/service/runnable.go:108](http://github.com/honeycombio/honeycomb-kubernetes-agent/service/runnable.go:108) +0x687
[github.com/honeycombio/honeycomb-kubernetes-agent/interval.(*Runner).run(0xc0000bee40)](http://github.com/honeycombio/honeycomb-kubernetes-agent/interval.(*Runner).run(0xc0000bee40))
	[github.com/honeycombio/honeycomb-kubernetes-agent/interval/interval_runner.go:72](http://github.com/honeycombio/honeycomb-kubernetes-agent/interval/interval_runner.go:72) +0xb6
[github.com/honeycombio/honeycomb-kubernetes-agent/interval.(*Runner).Start(0xc0000bee40)](http://github.com/honeycombio/honeycomb-kubernetes-agent/interval.(*Runner).Start(0xc0000bee40))
	[github.com/honeycombio/honeycomb-kubernetes-agent/interval/interval_runner.go:50](http://github.com/honeycombio/honeycomb-kubernetes-agent/interval/interval_runner.go:50) +0x1f5
[github.com/honeycombio/honeycomb-kubernetes-agent/service.(*Service).Start.func1()](http://github.com/honeycombio/honeycomb-kubernetes-agent/service.(*Service).Start.func1())
	[github.com/honeycombio/honeycomb-kubernetes-agent/service/service.go:144](http://github.com/honeycombio/honeycomb-kubernetes-agent/service/service.go:144) +0x25
created by [github.com/honeycombio/honeycomb-kubernetes-agent/service.(*Service).Start](http://github.com/honeycombio/honeycomb-kubernetes-agent/service.(*Service).Start)
	[github.com/honeycombio/honeycomb-kubernetes-agent/service/service.go:143](http://github.com/honeycombio/honeycomb-kubernetes-agent/service/service.go:143) +0x5af
```
Logs have been disabled, all we are attempting to gather with this agent are node and pod metrics
```yaml
watchers: []
metrics:
  enabled: true
  dataset: kubernetes-metrics
  clusterName: prod-usw2-kubernetes
  metricGroups:
    - node
    - pod
```

**Comment by robbkidd** [comment]
Are limits or requests resource keys present within the resultant spec for pods in the daemonset, possibly with empty string values? We have only been able to replicate this panic with sample data containing unparseable values for a limit.
